// src/core/state/index.js
// Public API for state management

// Store core
export {
  store,
  StateStore,
  createInitialState,
  getState,
  setState,
  get,
  set,
  subscribe,
  batch,
  reset
} from './store.js';

// Selectors (read-only)
export {
  getProject,
  getProjectName,
  getProjectMetadata,
  getSlides,
  getSlideCount,
  getSlideAt,
  getSelectedSlide,
  getSelectedSlideIndex,
  getTheme,
  getThemeBase,
  getThemeOverrides,
  getUIState,
  isSidebarCollapsed,
  isEditorCollapsed,
  getEditorHeight,
  getCurrentSidebarTab,
  getCurrentEditorTab,
  isResizingEditor,
  getDraggedIndex,
  getSelectedTemplate,
  hasUnsavedChanges,
  isProjectSaved,
  getPlayerSlideIndex,
  getPlayerResizeObserver,
  getActiveColorPicker,
  isSpectrumDragging,
  getOriginalColorValue,
  wasColorOverridden,
  isGapiReady,
  isGisReady,
  isDriveInitialized
} from './selectors.js';

// Actions (mutations)
export {
  setProject,
  setProjectName,
  setProjectMetadata,
  setSlides,
  setSelectedSlideIndex,
  updateSlideData,
  addSlide,
  removeSlide,
  duplicateSlide,
  moveSlide,
  setTheme,
  setThemeBase,
  setThemeOverrides,
  setThemeColor,
  removeThemeColor,
  resetThemeColors,
  setSidebarCollapsed,
  setEditorCollapsed,
  setEditorHeight,
  setCurrentSidebarTab,
  setCurrentEditorTab,
  setIsResizingEditor,
  setDraggedIndex,
  setSelectedTemplate,
  setHasUnsavedChanges,
  markAsChanged,
  clearUnsavedChanges,
  setPlayerSlideIndex,
  setPlayerResizeObserver,
  setActiveColorPicker,
  setSpectrumDragging,
  setOriginalColorValue,
  setWasColorOverridden,
  setGapiReady,
  setGisReady,
  setDriveInitialized
} from './actions.js';
